// utils/priceList.js
module.exports = [
  { product: "Boom Barrier", brand: "Essl", price: 25000 },
  { product: "Boom Barrier", brand: "Came", price: 3400 },
  { product: "Boom Barrier", brand: "ZKT", price: 2345 },
  { product: "Boom Barrier", brand: "Hikvision", price: 25000 },
  { product: "Boom Barrier", brand: "Honeywell", price: 3400 },
  { product: "Swing Barrier", brand: "Essl", price: 2345 },
  { product: "Swing Barrier", brand: "Came", price: 25000 },
  { product: "Swing Barrier", brand: "ZKT", price: 3400 },
  { product: "Swing Barrier", brand: "Hikvision", price: 2345 },
  { product: "Swing Barrier", brand: "Honeywell", price: 25000 },
  { product: "Flap Barrier", brand: "Essl", price: 3400 },
  { product: "Flap Barrier", brand: "Came", price: 2345 },
  { product: "Flap Barrier", brand: "ZKT", price: 25000 },
  { product: "Flap Barrier", brand: "Hikvision", price: 3400 },
  { product: "Flap Barrier", brand: "Honeywell", price: 2345 },
  { product: "Turnstile", brand: "Essl", price: 25000 },
  { product: "Turnstile", brand: "Came", price: 3400 },
  { product: "Turnstile", brand: "ZKT", price: 2345 },
  { product: "Turnstile", brand: "Hikvision", price: 25000 },
  { product: "Turnstile", brand: "Honeywell", price: 3400 },
  { product: "Baggage Scanner", brand: "Essl", price: 2345 },
  { product: "Baggage Scanner", brand: "Came", price: 25000 },
  { product: "Baggage Scanner", brand: "ZKT", price: 3400 },
  { product: "Baggage Scanner", brand: "Hikvision", price: 2345 },
  { product: "Baggage Scanner", brand: "Honeywell", price: 25000 },
  { product: "Metal Detector", brand: "Essl", price: 3400 },
  { product: "Metal Detector", brand: "Came", price: 2345 },
  { product: "Metal Detector", brand: "ZKT", price: 25000 },
  { product: "Metal Detector", brand: "Hikvision", price: 3400 },
  { product: "Metal Detector", brand: "Honeywell", price: 2345 },
  { product: "Bollard System", brand: "Essl", price: 25000 },
  { product: "Bollard System", brand: "Came", price: 3400 },
  { product: "Bollard System", brand: "ZKT", price: 2345 },
  { product: "Bollard System", brand: "Hikvision", price: 25000 },
  { product: "Bollard System", brand: "Honeywell", price: 3400 },
  { product: "Home Automation", brand: "Essl", price: 2345 },
  { product: "Home Automation", brand: "Came", price: 25000 },
  { product: "Home Automation", brand: "ZKT", price: 3400 },
  { product: "Home Automation", brand: "Hikvision", price: 2345 },
  { product: "Home Automation", brand: "Honeywell", price: 25000 },
];
